version: '3'

networks:
  default:
    driver: bridge

volumes:
  db-postgres:

services:
  postgres:
    container_name: db_postgres
    image: postgres:9.6.7
    environment:
      - PGDATA=php_tutorial
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=demo

    ports:
      - 5430:5432
    volumes:
      - db-postgres:/var/lib/postgresql/data
    tty: true
